In [1]:
import numpy as np
import torch

In [2]:
# 数组、nparray, tensor 之间的互相转换
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data=data)
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print("========= x_data ===========")
print(x_data)
print("========= np_array ===========")
print(np_array)
print("========= x_np ===========")
print(x_np)

========= x_data ===========
tensor([[1, 2],
        [3, 4]])
========= np_array ===========
[[1 2]
 [3 4]]
========= x_np ===========
tensor([[1, 2],
        [3, 4]])


In [3]:
# 继承之前的 shape 和数据类型
x_ones = torch.ones_like(x_data)
print("========= x_ones ===========")
print(x_ones)

# 继承之前的 shape，并显式指定新的数据类型
x_rand = torch.rand_like(x_data, dtype=torch.float)
print("========= x_rand ===========")
print(x_rand)

========= x_ones ===========
tensor([[1, 1],
        [1, 1]])
========= x_rand ===========
tensor([[0.8876, 0.9421],
        [0.4022, 0.7740]])


In [4]:
# 根据 shape 生成 tensor
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print("========= rand_tensor ===========")
print(rand_tensor)
print("========= ones_tensor ===========")
print(ones_tensor)
print("========= zeros_tensor ===========")
print(zeros_tensor)

========= rand_tensor ===========
tensor([[0.8823, 0.3751, 0.7179],
        [0.0544, 0.1165, 0.3968]])
========= ones_tensor ===========
tensor([[1., 1., 1.],
        [1., 1., 1.]])
========= zeros_tensor ===========
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
# 获取 tensor 的各种属性
print(f"shape of tensor: {ones_tensor.shape}")
print(f"datatype of tensor: {ones_tensor.dtype}")
print(f"device tensor is stored on: {ones_tensor.device}")

shape of tensor: torch.Size([2, 3])
datatype of tensor: torch.float32
device tensor is stored on: cpu


In [6]:
# 对 tensor 进行操作

# 转移到 GPU/MPS
if torch.backends.mps.is_available():
    print("moving ones_tensor to mps (Mac GPU)")
    ones_tensor = ones_tensor.to('mps')
elif torch.cuda.is_available():
    print("moveing ones_tensor to cuda")
    ones_tensor = ones_tensor.to('cuda')

print(f"device tensor is stored on: {ones_tensor.device}")

moving ones_tensor to mps (Mac GPU)
device tensor is stored on: mps:0


In [7]:
# tensor 索引和切片
tensor = torch.ones(4,4)
print(f"first row: {tensor[0]}") # 第一行
print(f"first column: {tensor[:, 0]}") # 第一列
print(f"last column: {tensor[..., -1]}") # 最后一列
tensor[:,1] = 0 # 第一列置为0
print(tensor)

first row: tensor([1., 1., 1., 1.])
first column: tensor([1., 1., 1., 1.])
last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [8]:
# tensor 合并, dim 按第 i 维拼接，只在第 i 维变长
t0 = torch.cat(tensors=[tensor, tensor, tensor], dim=0)
print(t0, t0.shape)
t1 = torch.cat(tensors=[tensor, tensor, tensor], dim=1) 
print(t1, t1.shape)
t2 = torch.cat(tensors=[tensor, tensor, tensor], dim=-1) 
print(t2, t2.shape)
t3 = torch.cat(tensors=[tensor, tensor, tensor], dim=-2) 
print(t3, t3.shape)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) torch.Size([12, 4])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]]) torch.Size([4, 12])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]]) torch.Size([4, 12])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
     

In [9]:
# tensor.stack 堆叠, dim 在第几维扩展一维并拼接
# t0 = torch.stack(tensors=[tensor, tensor, tensor], dim=0)
# print(t0)
# t1 = torch.stack(tensors=[tensor, tensor, tensor], dim=1)
# print(t1)
# t2 = torch.stack(tensors=[tensor, tensor, tensor], dim=-1)
# print(t2)
# t3 = torch.stack(tensors=[tensor, tensor, tensor], dim=-2)
# print(t3)
print(tensor)
print(tensor.shape)
t4 = torch.stack(tensors=[tensor, tensor, tensor], dim=1)
print(t4.shape)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
torch.Size([4, 4])
torch.Size([4, 3, 4])


In [10]:
# 数学运算
print(f"tensor: {tensor}")

# tensor.T 对二维张量（矩阵）做转置（行列互换），shape 变成 (n, m) → (m, n)。
print(f"tensor.T: {tensor.T}")

# @ 做矩阵乘法（不是逐元素乘法），常用于神经网络的全连接层、特征相关性等
y1 = tensor @ tensor.T
# @ 运算符和 .matmul() 完全等价，底层都调用 BLAS（高效线性代数库）做高性能乘法。
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
# 和上面一样，但指定结果保存在 y3 里，避免分配新内存，提升性能（尤其大张量时）。
torch.matmul(tensor, tensor.T, out=y3)
print("========= y1 ==========")
print(y1)
print("========= y2 ==========")
print(y2)
print("========= y3 ==========")
print(y3)

# 两个 shape 完全相同的张量，每个元素相乘，结果 shape 不变。
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print("========= z1 ==========")
print(z1)
print("========= z2 ==========")
print(z2)
print("========= z3 ==========")
print(z3)

# 对所有元素求和，结果是一个 0 维张量（tensor(XX)）。
agg = tensor.sum()
print(agg, type(agg))
# 把单元素（0 维）张量转换为原生 Python 数值（如 float）。
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor.T: tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
========= y1 ==========
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
========= y2 ==========
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
========= y3 ==========
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
========= z1 ==========
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
========= z2 ==========
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
========= z3 ==========
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]

In [14]:
print("========= tensor ==========")
print(tensor)

tensor.add_(5) # 原地修改 tensor
print(tensor)

tensor_add_5 = tensor.add(5) # 返回修改后的
print(tensor)
print(tensor_add_5)

========= tensor ==========
tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])
tensor([[16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.]])
tensor([[16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.]])
tensor([[21., 20., 21., 21.],
        [21., 20., 21., 21.],
        [21., 20., 21., 21.],
        [21., 20., 21., 21.]])


In [16]:
# tensor 转 numpy
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

# 修改 tensor 会同步影响 numpy
t.add_(5)
print(n)

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
[6. 6. 6. 6. 6.]


In [20]:
# numpy 转 tensor
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n) # 修改 n 一样会同步影响 t
print(t)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
